In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


# central  tendency

mean
median
mode

In [5]:
m = np.random.randint(7,10,20)   # it create a random no. list between 7 and 10 . total no. of item in list is 20.
print(m)

[8 9 9 7 7 8 8 8 7 9 8 8 7 7 7 8 8 8 8 9]


### Mean

Mean is the sum of the value of each observation in a dataset divided by the number of observation.$$ mean = sum of elements/no of elments$$


In [6]:
 np.mean(m)   # it calculate the mean of list m

7.9

### Median


Meadian is the middle value in distribution when the value are arranged in ascending order or decending order.
        (n/2)th observation when list is odd
        ((n+1)/2)th observation when list is even

In [7]:
m.sort()
m

array([7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9])

In [8]:
np.median(m)  # it calculates the median of list m.

8.0

### Mode

Mode is the most commonly occuring value in a distribution.

In [9]:
from statistics import mode

mode(m)       # it calculate the mode of list m.

8

## Poplation and Sample

### Population

In [10]:
population = np.random.randint(10,20,100)
population

array([17, 12, 16, 13, 12, 19, 15, 19, 10, 13, 19, 11, 13, 13, 12, 12, 17,
       11, 11, 19, 15, 13, 19, 16, 16, 14, 19, 15, 13, 15, 19, 14, 19, 11,
       17, 19, 12, 11, 18, 13, 12, 16, 14, 12, 17, 12, 18, 12, 12, 10, 16,
       13, 15, 16, 17, 17, 14, 19, 14, 11, 13, 15, 17, 13, 13, 10, 11, 11,
       14, 16, 14, 13, 16, 16, 18, 17, 17, 17, 12, 13, 12, 16, 11, 10, 14,
       11, 12, 11, 14, 15, 14, 17, 11, 16, 14, 16, 15, 19, 12, 18])

In [11]:
np.mean(population)

14.43

In [12]:
np.median(population)

14.0

In [13]:
from statistics import mode

mode(population)

12

### Sample

sample is the subset of population


In [14]:
sample = np.random.choice(population,20)
sample

array([14, 17, 11, 13, 11, 17, 11, 16, 14, 12, 11, 16, 12, 12, 14, 15, 11,
       11, 17, 19])

In [15]:
np.mean(sample)

13.7

In [16]:
np.median(sample)

13.5

In [17]:
mode(sample)

11

In [18]:
sample_1 = np.random.choice(population, 15)
sample_2 = np.random.choice(population, 15)
sample_3 = np.random.choice(population, 15)
sample_4 = np.random.choice(population, 15)

In [19]:
all_sample = [sample,sample_1,sample_2,sample_3,sample_4]
sample_mean = []

for i in all_sample:
    sample_mean.append(np.mean(i))
    
sample_mean

[13.7, 14.133333333333333, 14.133333333333333, 15.333333333333334, 13.6]

In [20]:
np.mean(sample_mean)

14.180000000000001

In [21]:
np.mean(population)

14.43

## Measure of Spread

Measure of spread has four categories which are following.
* Range
* Quartile
* Variance
* Standard Deviation

### Range

 Range give us how well data spread out.
 To calculate this we get a highest value in the dataset and the lowest value in the dataset and find the differene between them.

In [23]:
n = np.random.randn(30)
n

array([ 0.73358428,  0.11812994, -1.0566796 , -0.26148857,  1.71243772,
        1.42311983, -0.66884779,  0.89434795, -0.44223951,  0.36674241,
        1.68465753,  0.80875254,  0.60803159,  0.01598236,  0.05840569,
       -0.07869085, -0.80947434,  0.15604329,  0.63549677,  1.91896348,
       -0.66505183, -1.21416952, -1.20146452, -0.23612922,  2.33424794,
       -1.12299861, -0.4991103 ,  0.70883274,  2.17986222,  1.03521253])

In [24]:
np.max(n) - np.min(n)  # it gives the range of dataset n.

3.5484174621798754

### Quartile

Quartile divide a rank-ordered data set into four equal parts.

In [26]:
# First Quartile
Q1 = np.percentile(n,25)

In [27]:
# Second Quartile
Q2 = np.percentile(n,50)

In [28]:
# Third Quartile
Q3 = np.percentile(n,75)

#### Interquartile range

IQP = Third Quaritle - First Quartile

In [30]:
IQR = Q3 - Q1
IQR

1.3578417014040207

## Variance

  It tells how Spread out (far away) a number is from the mean

In [31]:
population = np.random.randn(100)

population

array([ 2.15335333, -1.12096837, -0.29621031, -0.34139842,  0.71350653,
        1.51962414, -0.39621234, -0.88244104,  0.597117  , -0.02608413,
        0.82408154,  1.28623879, -1.28250367,  2.03073088, -2.84863031,
       -0.02618878,  0.90062568,  0.23278286, -0.73287521,  0.56819489,
       -0.51111688, -0.5100441 , -0.57613013,  1.71091833, -1.16302846,
       -2.15346842,  1.45041695,  0.949254  , -1.06745212,  0.50192048,
       -0.97515274, -0.2382164 , -0.6132923 ,  1.30111156, -0.82010445,
        0.58189313,  0.64595441,  2.44085814, -0.48252653, -0.84608929,
       -0.2475148 , -1.33517857, -0.46456983,  1.46366633, -0.59523732,
       -0.41498262, -0.26471548, -0.22456379,  0.76409913,  0.52143682,
       -0.39113302,  1.18508288, -0.00680177,  0.28320049, -0.14813806,
        0.11262425,  0.91600759, -1.29554018,  0.82953396, -1.98737565,
       -0.29872556,  0.50371121,  0.87963704,  0.02892701, -0.91914536,
       -0.41405524, -1.30139939, -0.01229968,  0.37634098,  0.89

In [33]:
sample = np.random.choice(population,30)
sample

array([ 0.56819489,  0.39395984,  0.01373887,  0.52143682, -0.26471548,
       -2.15346842,  0.50371121,  0.82953396, -1.98737565,  0.597117  ,
       -1.43828045, -0.39621234, -0.5100441 ,  0.56819489,  1.46366633,
       -1.12096837,  0.02892701, -0.26471548,  0.28414868,  0.01373887,
        1.71091833, -1.33517857,  0.50371121,  0.50371121, -0.2475148 ,
       -1.12096837, -1.11930842, -0.04306759,  0.90062568,  0.87963704])

In [34]:
np.var(population)   # it calculate the variance of population

0.9323020594919019

In [35]:
np.var(sample)  # if calculate the variance of sample

0.8780540523744494

## Standard Deviation

The Square root of the variance is the Standard Deviation.While variance gives you a rough idea of spread. The standard deviation  is more concrete , gives you exact distances from the mean

In [36]:
np.std(population)   # it gives the standard deviation for population

0.9655579006418528

In [37]:
np.std(sample)    # it gives the standard deviation for sample

0.9370453843728432